### PR TITLE
stub of agency details page

### PR DESCRIPTION
**Pull request by lisaam**
Should this be "agency detail" or agency details" with an S? I think the plural makes for sense as a stand-alone page title.
Marco indicated that all pages should have at least on tab as this can be leveraged for archiving.

### CODE REVIEW

**Comment by siempa** [comment]
Should be Agency Details.

**Comment by lisaam** [comment]
Updated file to summary (from details)

**Comment by avaleske** [comment]
Accidentally merged #36 into this branch instead of master, so the commit history is a mess. Sorr about that. Merging this into master now.

**Comment by siempa** [comment]
Probably would never have noticed.

**Pull request merged**
